install(FILES broker_acl_file.dict DESTINATION ${OUT})
install(FILES broker_acl_file_seed_corpus.zip DESTINATION ${OUT})
install(FILES broker_conf.dict DESTINATION ${OUT})
install(FILES broker_fuzz_proxy_v1_seed_corpus.zip DESTINATION ${OUT})
install(FILES broker_fuzz_proxy_v2_seed_corpus.zip DESTINATION ${OUT})
install(FILES broker_fuzz_test_config_seed_corpus.zip DESTINATION ${OUT})
install(FILES broker_password_file_seed_corpus.zip DESTINATION ${OUT})
install(FILES broker_psk_file_seed_corpus.zip DESTINATION ${OUT})
install(FILES broker_queue_msg_seed_corpus.zip DESTINATION ${OUT})
install(FILES dynsec_config_seed_corpus.zip DESTINATION ${OUT})
